// ─── Greetings Pool ───────────────────────────────────────────────────────────
// 25–30 options per time slot, picked randomly each page load.

export const GREETINGS = {
    morning: [
        (n) => `Good morning, ${n}! ☀️`,
        (n) => `Rise and shine, ${n}! 🌅`,
        (n) => `Morning, ${n}! Let's crush it today 💪`,
        (n) => `Hey ${n}! Fresh day, fresh wins ✨`,
        (n) => `Good morning, ${n}! The early bird gets things done 🐦`,
        (n) => `Morning energy loading… ☕ Good morning, ${n}!`,
        (n) => `Wakey-wakey, ${n}! Big things await 🚀`,
        (n) => `A brand new day, ${n}! Make it count 🌄`,
        (n) => `Hello, ${n}! Your meetings won't run themselves — let's go! 📅`,
        (n) => `Good morning, ${n}! Starting strong 💡`,
        (n) => `Top of the morning, ${n}! ☕ You've got this`,
        (n) => `Morning, ${n}! Tasks won't complete themselves 😄`,
        (n) => `${n}! Another morning, another chance to win 🏆`,
        (n) => `Rise up, ${n}! Today's goals are waiting ⚡`,
        (n) => `Good morning, ${n}! Let's turn plans into progress 🗓️`,
        (n) => `Morning, ${n}! The team needs you 💼`,
        (n) => `${n}! Sunrise check-in complete ☀️ Ready for action!`,
        (n) => `Morning, ${n}! Fuel up ☕ — it's going to be a great day`,
        (n) => `Hey ${n}! New day, new opportunities 🌿`,
        (n) => `Good morning, ${n}! Let's make today productive 🎯`,
        (n) => `${n}! Up and at 'em — the dashboard awaits 📊`,
        (n) => `Morning, ${n}! Your focus sets the tone for the team 🧠`,
        (n) => `Good morning, ${n}! Small steps today = big wins tomorrow 🪜`,
        (n) => `Hey there, ${n}! Morning motivation: you've already started by showing up 🌟`,
        (n) => `Morning, ${n}! Let's make meetings matter today 🎙️`,
    ],

    afternoon: [
        (n) => `Good afternoon, ${n}! 🚀`,
        (n) => `Hey ${n}! Midday check-in 🎯`,
        (n) => `Afternoon, ${n}! Stay in the zone ⚡`,
        (n) => `Good afternoon, ${n}! Half the day down — let's finish strong 💪`,
        (n) => `Hey ${n}! Afternoon slump? Not today 🔥`,
        (n) => `${n}! Lunchtime energy boost incoming 🥗`,
        (n) => `Afternoon, ${n}! Keep the momentum going 🏃`,
        (n) => `Good afternoon, ${n}! Your best work might still be ahead 🌤️`,
        (n) => `Hey ${n}! Crushing it this afternoon? Let's check 📊`,
        (n) => `${n}! Afternoon vibes — focus mode: ON 🧠`,
        (n) => `Good afternoon, ${n}! The finish line is in sight 🏁`,
        (n) => `Hey ${n}! Post-lunch productivity incoming 🚀`,
        (n) => `Afternoon, ${n}! Deep work hour? Let's go 🎧`,
        (n) => `${n}! Half-day done, second wind activated ⚡`,
        (n) => `Good afternoon, ${n}! Time to tackle those pending tasks 📋`,
        (n) => `Hey ${n}! Afternoon is peak performance time — own it 💼`,
        (n) => `${n}! Mid-afternoon check — you're doing great 🌟`,
        (n) => `Good afternoon, ${n}! Action items don't clear themselves 😄`,
        (n) => `Afternoon, ${n}! One task at a time wins the race 🐢`,
        (n) => `Hey ${n}! Your afternoon mission, should you choose to accept… 🎯`,
        (n) => `Good afternoon, ${n}! Meetings reviewed, tasks assigned — let's roll 🎬`,
        (n) => `${n}! Afternoon momentum: it's contagious. Spread it 🌊`,
        (n) => `Afternoon, ${n}! Less talking, more doing — let's see those wins 🏆`,
        (n) => `Hey ${n}! The best time to close a task is right now ⏰`,
        (n) => `Good afternoon, ${n}! Halfway through — still plenty of time to shine ✨`,
    ],

    evening: [
        (n) => `Good evening, ${n}! 🌙`,
        (n) => `Evening, ${n}! Wrapping up strong 🌆`,
        (n) => `Hey ${n}! 🦉 Evening check-in`,
        (n) => `Good evening, ${n}! How did today treat you? 🌇`,
        (n) => `Evening, ${n}! Time to close the loop on today 📌`,
        (n) => `Hey ${n}! The city lights say it's evening — you say it's productive 🌃`,
        (n) => `Good evening, ${n}! Last sprint of the day 🏃`,
        (n) => `Evening check-in, ${n}! Let's see those completed tasks 🎉`,
        (n) => `${n}! Evening mode: reflect, review, and prepare 📒`,
        (n) => `Good evening, ${n}! Sunset goals are still goals 🌅`,
        (n) => `Hey ${n}! Evening hustle: optional but legendary 💫`,
        (n) => `Evening, ${n}! You've come a long way today 🛤️`,
        (n) => `Good evening, ${n}! A few more tasks and then rest — you've earned it 🛋️`,
        (n) => `${n}! End-of-day energy — let's finish what we started ✅`,
        (n) => `Evening, ${n}! Review today's wins before signing off 🏅`,
        (n) => `Good evening, ${n}! The best teams debrief before they rest 📝`,
        (n) => `Hey ${n}! Evening glow — and your progress glows too 🌟`,
        (n) => `${n}! Golden hour productivity — make it count 🌻`,
        (n) => `Good evening, ${n}! Today's effort is tomorrow's advantage 📈`,
        (n) => `Evening, ${n}! A task done today is a weight off tomorrow ⚖️`,
        (n) => `Hey ${n}! Wind down right — review your day 🌙`,
        (n) => `${n}! Good evening — you're closer to your goals than yesterday 🎯`,
        (n) => `Evening, ${n}! Team summary time — let's see the numbers 📊`,
        (n) => `Good evening, ${n}! Consistency today = excellence tomorrow ✨`,
        (n) => `Hey ${n}! Don't let the sunset set before your tasks do 🌄`,
    ],

    night: [
        (n) => `Still at it, ${n}? 🌌`,
        (n) => `Late-night grind, ${n}! 💡`,
        (n) => `Burning midnight oil, ${n}! 🔥`,
        (n) => `${n}! Night owl mode: activated 🦉`,
        (n) => `The office may be asleep, but not ${n} 🌙`,
        (n) => `Midnight warrior, ${n}? Respect 🙌`,
        (n) => `${n}! Late nights build legends 🌌`,
        (n) => `Night check-in, ${n}! Stars are watching you work ⭐`,
        (n) => `Still going, ${n}? The grind respects no clock 🕐`,
        (n) => `${n}! Late-night clarity is real — use it wisely 🧠`,
        (n) => `Hey ${n}! The world's quiet. Your focus isn't 🔇`,
        (n) => `${n}! Burning the midnight oil… and making it count 💪`,
        (n) => `Night mode, ${n}! Dark theme + dark hours = deep work 🖥️`,
        (n) => `${n}! Some of the best ideas happen after midnight 💡`,
        (n) => `Hey ${n}! Night sessions hit different — let's see those insights 🌠`,
        (n) => `${n}! The moon's your co-worker tonight 🌕`,
        (n) => `Still here, ${n}? The most dedicated always are 🏅`,
        (n) => `${n}! Night shift: optional, but legendary 🦸`,
        (n) => `Burning bright, ${n}! Even at this hour 🕯️`,
        (n) => `Hey ${n}! Not all heroes work 9–5. Keep going 🌙`,
        (n) => `${n}! Late night = less distractions = more done ⚡`,
        (n) => `Night check-in, ${n}! The quieter the hour, the louder the work 📣`,
        (n) => `${n}! Stars are out — and so is your dedication 🌟`,
        (n) => `Late night energy, ${n}! Almost there — finish strong 🏁`,
        (n) => `${n}! The world can wait — your goals can't 🌌`,
    ],
};

export const getGreeting = (name) => {
    const h = new Date().getHours();
    const pool =
        h >= 5  && h < 12 ? GREETINGS.morning   :
        h >= 12 && h < 18 ? GREETINGS.afternoon  :
        h >= 18 && h < 22 ? GREETINGS.evening    :
                            GREETINGS.night;
    return pool[Math.floor(Math.random() * pool.length)](name || 'there');
};
